### ISSUE TITLE
Solandra doesn't build against Cassandra 1.0.1

### ISSUE THREAD

**Issue by jasonmk** [tjake/Solandra#144]
I get the following output when I try to build Solandra against Cassandra 1.0.1:

```
compile:
    [javac] /usr/src/tjake-Solandra-462c13a/build.xml:134: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 35 source files to /usr/src/tjake-Solandra-462c13a/build/classes
    [javac] /usr/src/tjake-Solandra-462c13a/src/lucandra/CassandraUtils.java:310: cannot find symbol
    [javac] symbol  : method getNonSystemTables()
    [javac] location: class org.apache.cassandra.config.DatabaseDescriptor
    [javac]         if (DatabaseDescriptor.getNonSystemTables().contains(keySpace))
    [javac]                               ^
    [javac] /usr/src/tjake-Solandra-462c13a/src/lucandra/CassandraUtils.java:332: cannot find symbol
    [javac] symbol  : method getNonSystemTables()
    [javac] location: class org.apache.cassandra.config.DatabaseDescriptor
    [javac]         if (DatabaseDescriptor.getNonSystemTables().contains(keySpace))
    [javac]                               ^
    [javac] /usr/src/tjake-Solandra-462c13a/src/solandra/SolandraComponent.java:96: cannot find symbol
    [javac] symbol  : method getNonSystemTables()
    [javac] location: class org.apache.cassandra.config.DatabaseDescriptor
    [javac]             if(! DatabaseDescriptor.getNonSystemTables().contains(CassandraUtils.keySpace) )
    [javac]                                    ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
```

It _appears_ like getNonSystemTables() was moved over to Schema.  I can get it to build by swapping out `DatabaseDescriptor` with `Schema.instance`.  The tests still pass.  I haven't tested yet to see if things actually work.  Working on that now.

**Comment by efalcao** [comment]
I ran into the same issue and made the same changes above. I was able to compile. Haven't been able to run tests yet either.

**Comment by benmccann** [comment]
Here are the changes necessary to get it to compile with 1.1
https://github.com/tjake/Solandra/pull/169
