### ISSUE TITLE
Build with Cassandra 0.7.5 failed

### ISSUE THREAD

**Issue by ecrxs** [tjake/Solandra#83]
compile:
    [javac] Compiling 31 source files to C:\software\Solandra\tjake-Solandra-b8e8389\build\classes
    [javac] C:\software\Solandra\tjake-Solandra-b8e8389\src\lucandra\VIntType.java:27: lucandra.VIntType is not abstract and does not override abstract method decompose(j
ava.lang.Object) in org.apache.cassandra.db.marshal.AbstractType
    [javac] public class VIntType extends AbstractType {
    [javac]        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED

**Comment by tjake** [comment]
The api changed for comparators. This class will need to be updated in Solandra

**Comment by ceocoder** [comment]
@ecrxs it should work now
